using System;
using System.Collections.Generic;
using System.Text;
using VSYASGUI_CommonLib;

namespace VSYASGUI_WFP_App.MVVM.ViewModels.FilePresenters
{
    /// <summary>
    /// Provides an interface to download a specific file.
    /// </summary>
    internal sealed class WorldBackupsFilePresenter : FilePresenter
    {
        public override string DirectoryTitle => "World Backups";

        public override string DirectoryDescription => "Contains the worlds that were generated by the /genbackup <world name> command. Make sure to wait until the server completes the backup, otherwise a partial backup may be downloaded.";

        protected override ApiRequest FileRequestFactoryMethod(string selectedFileName)
        {
            return RequestFactory.MakeBackupDownloadRequest(selectedFileName);
        }

        protected override ApiRequest DirectoryContentsRequest()
        {
            return RequestFactory.MakeBackupDirectoryRequest();
        }
    }
}
